"""empty message

Revision ID: 943288b55818
Revises: b518aec40f0c
Create Date: 2020-03-03 15:03:44.038617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '943288b55818'
down_revision = 'b518aec40f0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
